using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("OPSIVRSystem.dll")]
[assembly: AssemblyDescriptionAttribute("")]
[assembly: AssemblyConfigurationAttribute("")]
[assembly: AssemblyCompanyAttribute("Ozeki Ltd.")]
[assembly: AssemblyProductAttribute("OPSIVRSystem.dll")]
[assembly: AssemblyCopyrightAttribute("Copyright © Ozeki Ltd. 2012")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: ComVisibleAttribute(false)]
[assembly: GuidAttribute("39de5efd-e156-48ba-828e-cbefadc1a47f")]
[assembly: AssemblyVersionAttribute("3.3.3.887")]

